class FlavorText
  def self.loading_messages
    [
      "Generating leaderboard...",
      "Crunching the numbers...",
      "Hold tight, I'm working on it...",
      "chugging the data juice",
      "chugging *Stat-Cola©*, for those who want to know things™",
      "that's numberwang!",
      "crunching the numbers",
      "munching the numbers",
      "gurgling the bits",
      "juggling the electrons",
      "chomping the bytes",
      "playing the photons on bass",
      "reticulating the splines",
      "rolling down data hills",
      "frolicking through fields of numbers",
      "skiing the data slopes",
      "zooming through the cyber-pipes",
      "grabbing the stats",
      "switching the dependent and independent variables",
      "flipping a coin to choose which axis to use",
      "warming up the powerhouse of the cell",
      "calculating significant figures...",
      "p-hacking the n value",
      "computing P = NP",
      "realizing P ≠ NP",
      "so, uh... come here often?",
      "*powertool noises*",
      "spinning violently around the y-axis",
      "serializing first-time coders experiences",
      "tokenizing personal experiences",
      "waking up the bits",
      "petting the bits",
      "testing patience",
      "npm installing 3 of 27594 packages",
      "spinning the rgbs",
      "Installing dependencies",
      "shoveling the overflowed pixels",
      ".split() === :large_blue_circle::large_green_circle::large_yellow_circle::large_orange_circle::red_circle::large_purple_circle: "
    ]
  end
end
